from .models import (
    SCHOOL_GROUPS,
    SCHOOL_STATUS,
    DOCUMENT_CREATION_TYPE,
    DOCUMENT_TYPE,
)

from .api import (
    MODELS,
    OPERATIONS_DB,
    BASE_LOCAL_URL,
    URI_PARENT_LIST,
    URI_DOCUMENT_LIST,
    URI_TEACHER_LIST,
    URI_CHILD_LIST,
    URI_GROUP_LIST,
)