FROM python:3.8.10-slim-buster
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN apt update &&apt-get install build-essential -y
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5008
COPY . .
CMD ["python", "main.py"]
