SCHOOL_STATUS = [('socio', 'socio'), ('pre socio', 'pre socio'),  ('collaborador', 'collaborador'), ]
SCHOOL_GROUPS = [('CdT', 'CdT'), ('Circulo de familia', 'Circulo de familia'), ('Equipo de Docente', 'Equipo de Docente')]

DOCUMENT_CREATION_TYPE = [('manual', 'manual'), ('auto', 'auto')]
BILL = 'BILL'
INSCRIPTION = 'INSCRIPTION'
CUOTAS_MATERIAL = 'CUOTAS y MATERIAL'
COMEDOR = 'COMEDOR'
ACOMPANAMIENTO = 'ACOMPAÑAMIENTO'
VENTAS = 'VENTAS'
FORMACIONES = 'FORMACIONES'
TALLERES_ACTIVIDADES_CAMPAMENTOS = 'TALLERES, ACTIVIDADES y CAMPAMENTOS'
EXTRAESCOLARES = 'EXTRAESCOLARES'
ATENCION_TEMPRANA = 'ATENCIÓN TEMPRANA'

DOCUMENT_TYPE = [
    (BILL, 'BILL'),
    (INSCRIPTION, 'INSCRIPTION'),
    (CUOTAS_MATERIAL, 'CUOTAS y MATERIAL'),
    (COMEDOR, 'COMEDOR'),
    (ACOMPANAMIENTO, 'ACOMPAÑAMIENTO'),
    (VENTAS, 'VENTAS'),
    (FORMACIONES, 'FORMACIONES'),
    (TALLERES_ACTIVIDADES_CAMPAMENTOS, 'TALLERES, ACTIVIDADES y CAMPAMENTOS'),
    (EXTRAESCOLARES, 'EXTRAESCOLARES'),
    (ATENCION_TEMPRANA, 'ATENCIÓN TEMPRANA')
]

PUBLIC_ACTIVITY = [('children', 'children'), ('parents', 'parents')]