# Generated by Django 4.1.2 on 2022-10-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volonteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_group', models.CharField(blank=True, choices=[('CdT', 'CdT'), ('Circulo de familia', 'Circulo de familia'), ('Equipo de Docente', 'Equipo de Docente')], max_length=20, null=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_leader', to='v1.parent')),
                ('members', models.ManyToManyField(related_name='members', to='v1.parent')),
                ('representative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_rep', to='v1.parent')),
            ],
            options={
                'verbose_name_plural': 'Volonteers',
                'ordering': ['work_group'],
            },
        ),
    ]
