# Generated by Django 4.1.2 on 2022-11-11 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='comment_for_parent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
