# Generated by Django 4.1.2 on 2023-01-14 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ask_inscription',
            field=models.ManyToManyField(blank=True, related_name='inscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
