# Generated by Django 4.1.2 on 2022-12-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ask_inscription',
            field=models.CharField(blank=True, choices=[('TEST', 'TEST')], max_length=100, null=True),
        ),
    ]
