# Generated by Django 4.1.2 on 2022-12-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='days_hour',
            field=models.CharField(blank=True, help_text='format: <day1>/<start_hour - stop_hour> , <day2>/<hours> example: Monday/15:30-16:30, Wednesday/15:30-16:30', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='details',
            field=models.TextField(blank=True, help_text='Explain to parents what is this activity', null=True),
        ),
    ]
