# Generated by Django 4.1.2 on 2022-12-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_activity_days_hour_activity_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='days_hour',
            field=models.CharField(blank=True, help_text='format: day1/start_hour-stop_hour, day2/hours example: Monday/15:30-16:30, Wednesday/15:30-16:30', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_all_year',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
