# Generated by Django 4.1.2 on 2022-11-11 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_activity_comment_for_parent_alter_activity_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pupil', to='v1.teacher'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='parent', to='v1.child'),
        ),
    ]
