# Generated by Django 4.1.2 on 2022-11-06 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_activity_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, null=True)),
                ('month', models.CharField(max_length=2, null=True)),
                ('content', models.JSONField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.activity')),
            ],
            options={
                'verbose_name_plural': 'Sheets',
                'ordering': ['activity', 'year', 'month'],
            },
        ),
    ]
