# Generated by Django 4.1.2 on 2022-12-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_activity_ask_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='nif',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
