# Generated by Django 4.1.2 on 2022-11-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='groups',
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group', to='v1.parent'),
        ),
    ]
