# Generated by Django 4.1.2 on 2022-12-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_alter_activity_days_hour_alter_activity_is_all_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='is_inscription_open',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
