# Generated by Django 4.1.2 on 2022-11-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_alter_child_tutor_alter_parent_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
