# Generated by Django 4.1.2 on 2022-11-11 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0004_alter_child_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parent', to='v1.child'),
        ),
    ]
