# Generated by Django 4.1.2 on 2022-12-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_alter_activity_is_inscription_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.CharField(choices=[('daily_price', 'daily price'), ('monthly_price', 'monthly price')], max_length=40, null=True),
        ),
    ]
