# Generated by Django 4.1.2 on 2022-12-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_activity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.CharField(choices=[('daily_price', 'daily price'), ('monthly_price', 'monthly price')], default='monthly_price', max_length=40, null=True),
        ),
    ]
