# Generated by Django 4.1.2 on 2022-11-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_alter_sheet_month_alter_sheet_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
