# Generated by Django 4.1.2 on 2022-11-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_inscription_open',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='nb_places_available',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
