# Generated by Django 4.1.2 on 2022-11-18 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0015_sheet_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='wife/husband of the user', null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.parent'),
        ),
    ]
