# Generated by Django 4.1.2 on 2022-11-18 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0016_parent_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='sheets',
        ),
        migrations.AddField(
            model_name='sheet',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='v1.archive'),
        ),
    ]
