# Generated by Django 4.1.2 on 2022-11-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0017_remove_archive_sheets_sheet_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='edit_permission',
            field=models.CharField(blank=True, choices=[('Creator only', 'Creator only'), ('Group only', 'Group only'), ('Several groups', 'Several groups'), ('All', 'All')], max_length=40, null=True),
        ),
    ]
