DOWNLOAD_FOLDER_BASE_PATH = "Download_temp_foler/"
TALK_TO_BOT = "@bot"
URL_DOCKER_CHAT = "http://localhost:2709"
URL_DOCKER_COMMANDS = "http://localhost:2404"

DOCKER_BASE_IMAGE_FILE = "Dockerfile_to_create_base_image"
DOCKER_BASE_IMAGE_NAME = "base_image_for_telegram:v1.0"
DOCKER_TELEGRAM_SERVER_IMAGE_FILE = "Dockerfile_to_create_telegram_basics"
DOCKER_TELEGRAM_SERVER_IMAGE_NAME = "telegram_server:v1.0"
DOCKER_COMPOSE_FILE = "telegram.yaml"
